name: Build Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    environment: buildPlugin
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: 17
    - name: Install .NET dependencies
      run: dotnet restore
    - name: Build plugin
      env:
        REQNROLL_TELEMETRY_ENABLED: 0
        APPINSIGHTSINSTRUMENTATIONKEY: ${{ secrets.APPINSIGHTS_KEY }}
      run: gradle :buildPlugin --stacktrace -PintellijPublishToken=none
    - name: dotnet-tests-report
      uses: zyborg/dotnet-tests-report@v1.4.3
      env:
        REQNROLL_TELEMETRY_ENABLED: 0
      with:
        report_name: plugin_tests
        report_title: Plugin Tests
        set_check_status_from_test_outcome: true
        project_path: src/dotnet/ReSharperPlugin.ReqnrollRiderPlugin.Tests/ReSharperPlugin.ReqnrollRiderPlugin.Tests.csproj
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Unpack Distribution
      shell: pwsh
      run: scripts/Unpack-Distribution.ps1
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ReqnrollPlugin
        path: build/distributions/unpacked